package com.mycompany.cnh2;

import Package2.Questoes;
import Package2.Exame;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JOptionPane;
import Package2.Questoes;

public class Prova extends javax.swing.JFrame {

    ArrayList<String> perguntas = new ArrayList<>();
    ArrayList<String> respostas = new ArrayList<>();
    String [] respostaSelecionada;
    int indice = 0;

    /**
     * Creates new form Prova
     */
    public Prova() {
        initComponents();
        colocarPerguntasNoArray();
        alterarQuestao(indice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        txtPergunta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        txtPergunta1 = new javax.swing.JLabel();
        btsair = new javax.swing.JButton();
        opcaoA = new javax.swing.JRadioButton();
        opcaoC = new javax.swing.JRadioButton();
        opcaoB = new javax.swing.JRadioButton();
        opcaoD = new javax.swing.JRadioButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prova teorica");

        txtPergunta.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPergunta.setForeground(new java.awt.Color(51, 51, 51));
        txtPergunta.setText("Responda as");

        txtQuestao.setEditable(false);
        txtQuestao.setColumns(20);
        txtQuestao.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtQuestao.setRows(5);
        jScrollPane1.setViewportView(txtQuestao);

        btnSalvar.setBackground(new java.awt.Color(51, 51, 51));
        btnSalvar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtPergunta1.setFont(new java.awt.Font("Century Gothic", 1, 45)); // NOI18N
        txtPergunta1.setForeground(new java.awt.Color(51, 51, 51));
        txtPergunta1.setText("Questões");
        txtPergunta1.setToolTipText("");
        txtPergunta1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btsair.setBackground(new java.awt.Color(255, 0, 0));
        btsair.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btsair.setForeground(new java.awt.Color(255, 255, 255));
        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcaoA);
        opcaoA.setText("A");
        opcaoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoAActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcaoC);
        opcaoC.setText("C");

        buttonGroup1.add(opcaoB);
        opcaoB.setText("B");
        opcaoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoBActionPerformed(evt);
            }
        });

        buttonGroup1.add(opcaoD);
        opcaoD.setText("D");
        opcaoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPergunta)
                            .addComponent(txtPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(opcaoA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(opcaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btsair)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(opcaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcaoA)
                    .addComponent(opcaoB)
                    .addComponent(opcaoC)
                    .addComponent(opcaoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btsair)
                        .addGap(34, 34, 34))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        indice++;
        alterarQuestao(indice);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        new Provas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btsairActionPerformed

    private void opcaoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoAActionPerformed
        // Os botoes estão separados
    }//GEN-LAST:event_opcaoAActionPerformed

    private void opcaoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoDActionPerformed

    private void opcaoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcaoBActionPerformed

    private void alterarQuestao(int i) {
        String pergunta = perguntas.get(i);

        txtQuestao.setText(pergunta);
    }

    private void colocarPerguntasNoArray() {
        
        perguntas.add("A utilização das vias por pessoas, veículos e animais é para fins de:\n" +
                "A) Circulação, parada e estacionamento.\n" +
                "B) Circulação e estacionamento.\n" +
                "C) Circulação, parada e operação de carga ou descarga.\n" +
                "D) Circulação, parada, estacionamento e operação de carga ou descar");
        respostas.add("D"); // 01
        
        perguntas.add("As praias abertas à circulação pública e as vias internas pertencentes aos condomínios "
                + "constituídos por unidades autônomas são, para efeito do Código de Trânsito Brasileiro, consideradas:\n" +
                "A) Vias terrestres.\n" +
                "B) Áreas autônomas.\n" +
                "C) Vias privativas.\n" +
                "D) Áreas restritas");
        respostas.add("A"); // 02
        
        perguntas.add("A função exercida pela PRF com o objetivo de garantir obediência às normas de trânsito é:\n" +
                "A) Fiscalização.\n" +
                "B) Operação.\n" +
                "C) Policiamento\n" +
                "D) Patrulhamento");
        respostas.add("D"); // 03
        
        perguntas.add("A fiscalização da gestão de trânsito poderá ser realizada com a utilização de aparelhos que, "
                + "quanto ao modo de operação, podem ser classificados em:\n" +
                "A) Automático e não automático.\n" +
                "B) Radar e medidor ótico.\n" +
                "C) Fixo, estátil, móvel e portátil.\n" +
                "D) Eletrônico e audiovisual.");
        respostas.add("C"); // 04
        
        perguntas.add("A idade mínima para conduzir um veículo automotor com capacidade acima de 20 passageiros é:\n" +
                "A) 20 anos.\n" +
                "B) 21 anos.\n" +
                "C) 18 anos.\n" +
                "D) 19 anos.");
        respostas.add("B"); // 05
        
        perguntas.add("Para habilitar-se na categoria D, o condutor deverá possuir no mínimo:\n" +
                "A) 1 ano na categoria B, ou 2 anos na categoria C.\n" +
                "B) 2 anos na categoria B, ou 1 ano na categoria C.\n" +
                "C) Somente 1 ano na categoria C.\n" +
                "D) Somente 1 ano na categoria B.");
        respostas.add("B"); // 06
        
        perguntas.add(" É considerado veículo de passageiro:\n" +
                "A) Carroça.\n" +
                "B) Caminhão.\n" +
                "C) Caminhonete.\n" +
                "D) Bicicleta");
        respostas.add("D"); // 07
        
        perguntas.add("As placas com as cores verde e amarela da Bandeira Nacional são usadas pelos veículos de representação pessoal do(s):\n" +
                "A) Governadores.\n" +
                "B) Presidente e Vice-Presidente da República.\n" +
                "C) Prefeitos.\n" +
                "D) Secretários municipais.");
        respostas.add("B"); // 08
        
        perguntas.add("No caso de transferência de propriedade, o prazo para o proprietário adotar as providências necessárias à efetivação da "
                + "expedição de novo Certificado de Registro de Veículo é de:\n" +
                "A) 15 dias.\n" +
                "B) De imediato.\n" +
                "C) 30 dias.\n" +
                "D) A qualquer tempo.");
        respostas.add("C"); // 09
        
        perguntas.add("Marca, modelo, ano de cor, número do chassi, são:\n" +
                "A) Acessórios do veículo.\n" +
                "B) Equipamentos obrigatórios.\n" +
                "C) Características legais e essenciais do veículo.\n" +
                "D) Elementos utilizados, somente, para controle das montadoras de veículos.");
        respostas.add("C"); // 10
        
        perguntas.add("A forma padrão do sinal de regulamentação é:\n" +
                "A) Retangular\n" +
                "B) Circular.\n" +
                "C) Quadrada\n" +
                "D) Hexagonal");
        respostas.add("B"); // 11
        
        perguntas.add(" As luzes de cores preestabelecidas são utilizadas para controle de fluxo de:\n" +
                "A) Somente para veículos de tração animal.\n" +
                "B) Somente para veículos de propulsão humana.\n" +
                "C) Estacionamento de veículos.\n" +
                "D) Pedestres e/ou veículos.");
        respostas.add("D"); // 12
        
        perguntas.add("As placas indicativas de sentido (direção) e de distância, de forma retangular, são apresentadas nas cores:\n" +
                "A) Verde e branca.\n" +
                "B) Preta e verde.\n" +
                "C) Preta e branca.\n" +
                "D) Branca e azul.");
        respostas.add("A"); // 13
        
        perguntas.add("A faixa de Travessia de Pedestre é um tipo de Marca denominada:\n" +
                "A) Longitudinal.\n" +
                "B) Canalização.\n" +
                "C) Transversal.\n" +
                "D) Controle de Estacionamento e/ou Parada.");
        respostas.add("C"); // 14
        
        perguntas.add("A linha que proibe ultrapassar para os dois sentidos denomina-se:\n" +
                "A) Simples seccionada.\n" +
                "B) Dupla seccionada.\n" +
                "C) Dupla contínua.\n" +
                "D) Dupla contínua/seccionada.");
        respostas.add("B"); // 15
        
        perguntas.add("As cores das luzes utilizadas para controle de fluxo de pedestres são:\n" +
                "A) Vermelha, amarela e verde.\n" +
                "B) Vermelha e amarela.\n" +
                "C) Vermelha e verde.\n" +
                "D) Amarela e verde.");
        respostas.add("C"); // 16
        
        perguntas.add("O condutor que for multado por desobedecer a sinalização de parada obrigatória, "
                + "terá anotado em seu prontuário a pontuação equivalente a:\n" +
                "A) Quatro pontos.\n" +
                "B) Três pontos.\n" +
                "C) Sete pontos.\n" +
                "D) Cinco pontos.");
        respostas.add("C"); // 17
        
        perguntas.add("A pena de detenção atribuída ao condutor que pratica homicídio culposo na direção do veículo automotor é de:\n" +
                "A) 2 a 4 anos.\n" +
                "B) 6 meses a 1 ano.\n" +
                "C) 6 meses a 2 anos.\n" +
                "D) 1 a 4 anos.");
        respostas.add("A"); // 18
        
        perguntas.add("Onde não houver sinalização regulamentadora, a velocidade máxima nas vias locais será:\n" +
                "A) 30 km/h.\n" +
                "B) 20 km/h.\n" +
                "C) 50 km/h.\n" +
                "D) 40 km/h.");
        respostas.add("A"); // 19
        
        perguntas.add("Antes de colocar o veículo em movimento, o condutor deve verificar as condições de funcionamento dos equipamentos de uso obrigatório:\n" +
                "A) Cinto de segurança e encosto de cabeça.\n" +
                "B) Todas as alternativas estão corretas.\n" +
                "C) Triângulo de segurança e pneu sobressalente.\n" +
                "D) Limpador de parabrisa e buzina");
        respostas.add("B"); // 20
        
        perguntas.add("Para evitar colisões nos cruzamentos é fundamental:\n" +
                "A) Aumentar a velocidade.\n" +
                "B) Olhar primeiro para a direita e avançar.\n" +
                "C) Respeitar a preferência.\n" +
                "D) Diminuir a velocidade e buzinar");
        respostas.add("C"); // 21
        
        perguntas.add("É atitude do condutor defensivo, quando ingerir bebida alcóolica:\n" +
                "A) Dirigir redobrando os cuidados.\n" +
                "B) Dirigir, somente, se estiver acompanhado.\n" +
                "C) Tomar banho bem frio ou molhar a cabeça para despertar, antes de começar a dirigir.\n" +
                "D) Não dirigir o veículo, pedindo a outro condutor habilitado que realize tal atitude");
        respostas.add("D"); // 22
        
        perguntas.add("A maioria dos acidentes está associada à condição adversa do condutor. A grande maioria deles é causada por:\n" +
                "A) Falhas mecânicas.\n" +
                "B) Deficiência da via.\n" +
                "C) Falta de sinalização.\n" +
                "D) Falhas humanas");
        respostas.add("D"); // 23
        
        perguntas.add("São tipos de direção defensiva:\n" +
                "A) Disciplinar e Legal.\n" +
                "B) Preventiva e Corretiva.\n" +
                "C) Eficiente e Utilitária.\n" +
                "D) Segura e Insegura");
        respostas.add("B"); // 24
        
        perguntas.add("A força que tende a jogar o veículo para fora da curva denomina-se:\n" +
                "A) Centrípeta.\n" +
                "B) Molecular.\n" +
                "C) Misteriosa.\n" +
                "D) Centrífuga");
        respostas.add("D"); // 25
        
        
        Questoes questoes = new Questoes();
        Random random = new Random();
        int numeroSorteado = random.nextInt(20);
        
        int linhas = questoes.armazenarQuestao().length;


        for (int i = 0; i < linhas; i++) {
            perguntas.add(questoes.armazenarQuestao()[numeroSorteado][0]);
            respostas.add(questoes.armazenarQuestao()[numeroSorteado][1]);
        }
    }
    
    public void adicionarResposta() {
        respostaSelecionada = new String [19];
            for (int i = 0; i < respostaSelecionada.length; i++) {
                if (opcaoA.isSelected()) {
                    respostaSelecionada[i] = "A";
                } else if (opcaoB.isSelected()) {
                    respostaSelecionada[i] = "B";
                } else if (opcaoC.isSelected()) {
                    respostaSelecionada[i] = "C";
                } else if (opcaoD.isSelected()) {
                   respostaSelecionada[i] = "D";
                }
            }
    }
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prova().setVisible(true);
            }
        });
    }

    //Metodos especiais
    
    public ArrayList<String> getPerguntas() {
        return perguntas;
    }

    public void setPerguntas(ArrayList<String> perguntas) {
        this.perguntas = perguntas;
    }

    public ArrayList<String> getRespostas() {
        return respostas;
    }

    public void setRespostas(ArrayList<String> respostas) {
        this.respostas = respostas;
    }

    public String[] getRespostaSelecionada() {
        return respostaSelecionada;
    }

    public void setRespostaSelecionada(String[] respostaSelecionada) {
        this.respostaSelecionada = respostaSelecionada;
    }

    public Prova(String[] respostaSelecionada) {
        this.respostaSelecionada = respostaSelecionada;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btsair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opcaoA;
    private javax.swing.JRadioButton opcaoB;
    private javax.swing.JRadioButton opcaoC;
    private javax.swing.JRadioButton opcaoD;
    private javax.swing.JLabel txtPergunta;
    private javax.swing.JLabel txtPergunta1;
    private javax.swing.JTextArea txtQuestao;
    // End of variables declaration//GEN-END:variables
}
