package com.mycompany.cnh2;

import Package2.*;
import static com.sun.tools.javac.tree.TreeInfo.args;
import javax.swing.JOptionPane;

public class Provas extends javax.swing.JFrame {
    int nota = 0;
    Sistema sistema = new Sistema();
    Exame exame = new Exame();
    private String[] args;
    /**
     * Creates new form Provas
     */
    public Provas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btteoria = new javax.swing.JButton();
        btsair = new javax.swing.JButton();
        btagendar = new javax.swing.JButton();
        btdatasnovas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Provas");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Realizar");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Provas");

        btteoria.setBackground(new java.awt.Color(51, 51, 51));
        btteoria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btteoria.setForeground(new java.awt.Color(255, 255, 255));
        btteoria.setText("Teórica");
        btteoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btteoriaActionPerformed(evt);
            }
        });

        btsair.setBackground(new java.awt.Color(204, 0, 0));
        btsair.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btsair.setForeground(new java.awt.Color(255, 255, 255));
        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });

        btagendar.setBackground(new java.awt.Color(51, 51, 51));
        btagendar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btagendar.setForeground(new java.awt.Color(255, 255, 255));
        btagendar.setText("Agendar outros testes");
        btagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagendarActionPerformed(evt);
            }
        });

        btdatasnovas.setBackground(new java.awt.Color(51, 51, 51));
        btdatasnovas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btdatasnovas.setForeground(new java.awt.Color(255, 255, 255));
        btdatasnovas.setText("Alterar data dos testes");
        btdatasnovas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdatasnovasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btagendar)
                            .addComponent(btteoria))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btdatasnovas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(btsair)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btteoria)
                .addGap(18, 18, 18)
                .addComponent(btagendar)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsair)
                    .addComponent(btdatasnovas))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btteoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btteoriaActionPerformed
      
        Testes.main(args);
        this.dispose();
    }//GEN-LAST:event_btteoriaActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        if(nota == 0){
            JOptionPane.showMessageDialog(null, "Nenhuma prova foi realizada");
            new Menu().setVisible(true);
            this.dispose();
        }
        if(nota == 1){
            JOptionPane.showMessageDialog(null, "Ainda existem provas pendentes, volte para realizar");
            new Menu().setVisible(true);
            this.dispose();
        }
        if(nota == 2){
            JOptionPane.showMessageDialog(null, "Você passou, parabens professor uhull!");
            new Menu().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btsairActionPerformed

    private void btagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagendarActionPerformed
        exame.agendarExame();
        nota++;
    }//GEN-LAST:event_btagendarActionPerformed

    private void btdatasnovasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdatasnovasActionPerformed
        exame.alterarDataExame();
    }//GEN-LAST:event_btdatasnovasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagendar;
    private javax.swing.JButton btdatasnovas;
    private javax.swing.JButton btsair;
    private javax.swing.JButton btteoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
