package com.mycompany.cnh2;

import Package2.*;
import static com.sun.tools.javac.tree.TreeInfo.args;
import javax.swing.JOptionPane;

public class SegundaT extends javax.swing.JFrame {
    int nota = 0;
    Sistema sistema = new Sistema();
    Exame exame = new Exame();
    private String[] args;
    /**
     * Creates new form Provas
     */
    public SegundaT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btteoria = new javax.swing.JButton();
        txtOi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btsair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Provas");

        btteoria.setBackground(new java.awt.Color(51, 51, 51));
        btteoria.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btteoria.setForeground(new java.awt.Color(255, 255, 255));
        btteoria.setText("2ª Tentativa");
        btteoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btteoriaActionPerformed(evt);
            }
        });

        txtOi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtOi.setForeground(new java.awt.Color(51, 51, 51));
        txtOi.setText("Infelizmente vc foi");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Reprovado");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btsair2.setBackground(new java.awt.Color(204, 0, 0));
        btsair2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btsair2.setForeground(new java.awt.Color(255, 255, 255));
        btsair2.setText("Sair");
        btsair2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btsair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOi)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btteoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                        .addComponent(btsair2)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtOi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btteoria)
                    .addComponent(btsair2))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btteoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btteoriaActionPerformed

        Testes1.main(args);
        this.dispose();
    }//GEN-LAST:event_btteoriaActionPerformed

    private void btsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsair2ActionPerformed
        new BemVindoo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btsair2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundaT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsair2;
    private javax.swing.JButton btteoria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtOi;
    // End of variables declaration//GEN-END:variables
}
